### PR TITLE
Cleanup code/Fix memory leak

### PR DESCRIPTION
**Pull request by TheCraftKid**
This removes a memory leak coming from App.class using a static `Context` and also removes that unnecessary class. 
It also simplifies the `MainActivity`'s layout and styles since the Android framework already provides what we need. Overall, this should reduce APK size.

### CODE REVIEW

**Comment by franciscofranco** [comment]
About https://github.com/franciscofranco/Demo-Mode-tile/pull/6/commits/bc79db0e81aa5cb598e8d1a34d60ef54ef916440 this is debatable. Yes Context _should_ never be static, this Context is a singleton because there is only one Application instance throughout the app's lifecycle. In this case there's just no need to pollute the code with arguments through functions where you can just access the singleton which won't leak. Context leaks are usually a bit more complex than just having a static object. So I'd prefer if we'd not submit this.

**Comment by franciscofranco** [comment]
About https://github.com/franciscofranco/Demo-Mode-tile/pull/6/commits/9591218e4efec1cafab6102030d69d4b275fbbe1 yes you're right, but I use the AppCompat for consistency. Even through out different framework versions there are inconsistencies through out different widgets and things can be different. Using AppCompat makes it all easy to maintain. And yes the framework gives you the Toolbar through the default style, but I like to have my own in case I need to change it somehow.

**Comment by franciscofranco** [comment]
I'm sorry you had all this work. I just checked and I have code in staging not pushed to the remote (no idea why) and my changes and these conflict. I'll close this. After I push the new code you can make more pull requests if you'd like!

**Comment by TheCraftKid** [comment]
Thanks for looking over this. While my work my be in vain, at least I learned something. :smile: 
I'm still a bit apprehensive about [`9591218`](https://github.com/franciscofranco/Demo-Mode-tile/commit/9591218e4efec1cafab6102030d69d4b275fbbe1) because I'd like to see the Toolbar separated from the rest of the activity to fit material design, but it is your app. :wink: 

Is there any ETA for the next update?

**Comment by franciscofranco** [comment]
But it fits material design just fine as it is, why do you think otherwise?
Maybe today :)

**Comment by TheCraftKid** [comment]
It was just that the current iteration reminds me of iOS where the entire screen was one flat surface instead of the Toolbar separating itself from the rest of the hierarchy, but oh well. :man_shrugging:

**Comment by TheCraftKid** [comment]
It was just that the current iteration reminds me of iOS where the entire screen was one flat surface instead of the Toolbar separating itself from the rest of the hierarchy, but oh well. :man_shrugging:

**Comment by franciscofranco** [comment]
But that's just because I'm not wrapping the toolbar with an AppBarLayout or adding an elevation to the toolbar... it's irrelevant.

**Pull request closed without merging**
